version: "3"

services:
  # Conteneur base de données
  db:
    image: mongo:5.0.5
    container_name: db
    volumes:
      # Ce volume permettra de préserver les données si la base de données doit évoluer. Ici, on
      # se base uniquement sur les données dans le dump, et ce volume n'est pas forcément nécessaire
      - ./data:/data/db
      # On monte le dump de la base de données dans un dossier du conteneur
      - ./dump/test:/dump/
      # On monte le script mongorestore.sh dans le dossier /docker-entrypoint-initdb.d, qui sera
      # lancé automatiquement au démarrage du conteneur.
      # Ce dossier d'entrypoint est une convention Docker, qui est au moins respectée pour tous les
      # conteneurs de base de données
      - ./dump/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh:ro
  # Conteneur frontend
  frontv1:
    # On construit directement le frontend, depuis le dossier ./front
    build: ./front/.
    container_name: front
    ports:
      - 80:80

  # Conteneur backend
  backv1:
    # On construit directement le backend, depuis le dossier ./back
    build: ./back/.

    container_name: back
    environment:
      - PORT=${PORT}
      - MONGO_HOST=${MONGO_HOST}
    ports:
      - 8080:8080

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - db
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db
